version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
  tests:   #creating another service to run test
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/app
    command: ["npm", "run", "test"]  #to overide the defaukt start command with a test command