name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - run: echo $DOCKER_PASSWORD | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      - run: docker build -t hollumighty/frontreal -f Dockerfile .
      - run: docker run -e CI=true hollumighty/frontreal npm test

 
      - run: docker push hollumighty/frontreal
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: DockerReact-app
          environment_name: DockerReact-app-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-111753924075
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip